export const zostelLocations = {
  North: [
    "Zostel Banikhet (Dalhousie)",
    "Zostel Chitkul",
    "Zostel Delhi",
    "Zostel Dharamkot",
    "Zostel Dobhi",
    "Zostel Kalpa",
    "Zostel Kasol (Ka..",
    "Zostel Leh",
    "Zostel Manali",
    "Zostel McLeodg..",
    "Zostel Mukteshwar",
    "Zostel Mussoorie ",
    "Zostel Pahalgam",
    "Zostel Pulga",
    "Zostel Rajgundha",
    "Zostel Rishikesh ",
    "Zostel Rishikesh",
    "Zostel Sangla",
    "Zostel Shangarh",
    "Zostel Shoja (Jibhi)",
    "Zostel Sissu",
    "Zostel Spiti",
    "Zostel Srinagar",
  ],
  South: ["Zostel Gokarna", "Zostel Munnar", "Zostel Ooty", "Zostel Wayanad"],
  East: ["Zostel Darjeeling", "Zostel Gangtok", "Zostel Kalimpong"],
  West: ["Zostel Jaipur", "Zostel Udaipur", "Zostel Jaisalmer"],
};

export const zostelPlusData = {
  North: [
    "Zostel Plus Bir",
    "Zostel Plus Kareri",
    "Zostel Plus Mussoorie (Kempty)",
    "Zostel Plus Nainital (Naina Range)",
    "Zostel Plus Rishikesh (Mohanchatti)",
  ],
  South: ["Zostel Plus Coorg", "Zostel Plus Ooty", "Zostel Plus Munnar"],
  East: ["Zostel Plus Kalimpong"],
  West: ["Zostel Plus Lonavala"],
};

export const homesData = {
  North: [
    "Zostel Homes Billing (Bir)",
    "Zostel Homes Bir",
    "Zostel Homes Cheog",
    "Zostel Homes Harabhag",
    "Zostel Homes Kotkhai",
    "Zostel Homes Laida",
    "Zostel Homes Leh (Stok)",
    "Zostel Homes Mashobra",
    "Zostel Homes Rajgundha",
    "Zostel Homes Ramgarh ",
    "Zostel Homes Rashil",
    "Zostel Homes Shimla",
    "Zostel Homes Theog",
    "Zostel Homes Tirthan ",
  ],
  South: ["Zostel Homes Wayanad", "Zostel Homes Coorg"],
  East: ["Zostel Homes Kalimpong", "Zostel Homes Sikkim"],
  West: ["Zostel Homes Udaipur", "Zostel Homes Mount Abu"],
};
export const zotripDatas = [
  "Experience Bali",
  "Experience Oman",
  "Experience Darjeeling & Sikkim",
  "Experience Full Moon Party Tha..",
  "Experience Annapurna Base Ca..",
  "Experience Almaty (Kazakhstan)",
  "Experience Georgia",
  "Experience Sri Lanka",
  "Experience Cherry Blossom Festival",
  "Experience Ziro Festival of Music",
  "Experience Andaman",
  "Experience Bhutan",
  "Experience Vietnam",
  "Experience Kerala",
  "Experience Zanskar",
  "Experience Chikkamagaluru",
];